### ISSUE TITLE
Compose Multiplatform

### ISSUE THREAD

**Issue by wakaztahir** [timeline-notes/compose-code-editor#6]

**Comment by hakanai** [comment]
Interested in this because I'm using Jetpack Compose to write a desktop app and would prefer not to have to write an entire code editor component myself. :)

**Comment by wakaztahir** [comment]
I can't do this for at least a month.

**Comment by wakaztahir** [comment]
just clone the repo to test it out , if it works on desktop then good.

**Comment by hakanai** [comment]
Yeah, the current master works fine. I'll look forward to the next release. :)

**Comment by wakaztahir** [comment]
Boom it's multiplatform , but dependency is only available with GitHub packages
